// save all data Apps practical

const allAppData = [
  {
    id: 1,
    img: "./src/images/apps-practical/app-practical-1.webp",
    title: "فیلیمو - تماشای فیلم و سریال",
    type: "سرگرمی",
    categories: "applications",
    appVolume: 20,
  },
  {
    id: 2,
    img: "./src/images/apps-practical/app-practical-2.webp",
    title: "ترب | بهترین قیمت بازار ",
    type: "خرید",
    categories: "applications",
    appVolume: 21,
  },
  {
    id: 3,
    img: "./src/images/apps-practical/app-practical-3.webp",
    title: "آپ کارت به کارت،خلافی خودرو،چک صیادی",
    type: "امور مالی",
    categories: "applications",
    appVolume: 22,
  },
  {
    id: 4,
    img: "./src/images/apps-practical/app-practical-4.webp",
    title: "اسنپ |Snapp سامانه هوشمند حمل و نقل",
    type: "رفت و آمد",
    categories: "applications",
    appVolume: 23,
  },
  {
    id: 5,
    img: "./src/images/apps-practical/app-practical-5.webp",
    title: "دیوار",
    type: "خرید",
    categories: "applications",
    appVolume: 24,
  },
  {
    id: 6,
    img: "./src/images/apps-practical/app-practical-6.webp",
    title: "اسنپ فود | سفارش غذا",
    type: "آشپزی و رستوران",
    categories: "applications",
    appVolume: 25,
  },
  {
    id: 7,
    img: "./src/images/apps-practical/app-practical-7.webp",
    title: "تپسی - درخواست آنلاین خودرو و پیک",
    type: "رفت و آمد",
    categories: "applications",
    appVolume: 26,
  },
  {
    id: 8,
    img: "./src/images/apps-practical/app-practical-8.webp",
    title: "فیلم‌نت - تماشای فیلم و سریال",
    type: "سرگرمی",
    categories: "applications",
    appVolume: 27,
  },
  {
    id: 9,
    img: "./src/images/apps-practical/app-practical-9.webp",
    title: "بلد — نقشه‌ و ‌مسیریاب",
    type: "رفت و آمد",
    categories: "applications",
    appVolume: 28,
  },
  {
    id: 10,
    img: "./src/images/apps-practical/app-practical-10.webp",
    title: "علی‌بابا | خرید بلیط، هتل و تور",
    type: "سفر",
    categories: "applications",
    appVolume: 29,
  },
  {
    id: 11,
    img: "./src/images/apps-practical/app-practical-11.webp",
    title: "آیتول (خلافی خودرو، بیمه، عوارض)",
    type: "امور مالی",
    categories: "applications",
    appVolume: 30,
  },
  {
    id: 12,
    img: "./src/images/apps-practical/app-practical-12.webp",
    title: "دیجی‌کالا | فروشگاه خرید آنلاین",
    type: "خرید",
    categories: "applications",
    appVolume: 19,
  },
  {
    id: 13,
    img: "./src/images/apps-practical/app-practical-13.webp",
    title: "پیندو | خرید و فروش بدون واسطه کالا",
    type: "خرید",
    categories: "applications",
    appVolume: 18,
  },
  {
    id: 14,
    img: "./src/images/apps-practical/app-practical-14.webp",
    title: "طاقچه | دانلود کتاب صوتی و الکترونیک",
    type: "کتاب و مطبوعات",
    categories: "applications",
    appVolume: 17,
  },
  {
    id: 15,
    img: "./src/images/apps-practical/app-practical-15.webp",
    title: "نشان | نقشه و مسیریاب ",
    type: "رفت و آمد",
    categories: "applications",
    appVolume: 20,
  },
  {
    id: 16,
    img: "./src/images/apps-practical/app-practical-16.webp",
    title: "سپهر360 | خرید بلیط هواپیما",
    type: "سفر",
    categories: "applications",
    appVolume: 29,
  },

  {
    id: 17,
    img: "./src/images/apps-bank/app-bank-1.webp",
    title: "همراه بانک ملت",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 11,
  },
  {
    id: 18,
    img: "./src/images/apps-bank/app-bank-2.webp",
    title: "همراه بام ملی",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 12,
  },
  {
    id: 19,
    img: "./src/images/apps-bank/app-bank-3.webp",
    title: "همراه بانک قرض الحنه مهر ایران",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 13,
  },
  {
    id: 20,
    img: "./src/images/apps-bank/app-bank-4.webp",
    title: "همراه بانک سپه",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 14,
  },
  {
    id: 21,
    img: "./src/images/apps-bank/app-bank-5.webp",
    title: "همراه بانک صادرات ایران",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 15,
  },
  {
    id: 22,
    img: "./src/images/apps-bank/app-bank-6.webp",
    title: "بلوبانک - بانک ولی دوست‌داشتنی",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 16,
  },
  {
    id: 23,
    img: "./src/images/apps-bank/app-bank-7.webp",
    title: "همراه بانک تجارت",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 17,
  },
  {
    id: 24,
    img: "./src/images/apps-bank/app-bank-8.webp",
    title: "همراه بانک کشاورزی",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 18,
  },
  {
    id: 25,
    img: "./src/images/apps-bank/app-bank-9.webp",
    title: "همراه بانک قرض الحسنه رسالت",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 19,
  },
  {
    id: 26,
    img: "./src/images/apps-bank/app-bank-10.webp",
    title: "ویپاد | تَرابانک پاسارگاد",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 22,
  },
  {
    id: 27,
    img: "./src/images/apps-bank/app-bank-11.webp",
    title: "موبایل بانک رفاه",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 21,
  },
  {
    id: 28,
    img: "./src/images/apps-bank/app-bank-12.webp",
    title: "همراه شهر پلاس",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 25,
  },
  {
    id: 29,
    img: "./src/images/apps-bank/app-bank-13.webp",
    title: "همراه بانک پست بانک",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 9,
  },
  {
    id: 30,
    img: "./src/images/apps-bank/app-bank-14.webp",
    title: "همراه بانک پاسارگاد (موبایل بانک)",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 10,
  },
  {
    id: 31,
    img: "./src/images/apps-bank/app-bank-15.webp",
    title: "فراز (همراه بانک ایران زمین)",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 11,
  },
  {
    id: 32,
    img: "./src/images/apps-bank/app-bank-16.webp",
    title: "پارسیان من (همراه بانک پارسیان)",
    type: "امور مالی",
    categories: "bankApps",
    appVolume: 12,
  },

  {
    id: 33,
    img: "./src/images/apps-entertainment/app-entertainment-1.webp",
    title: "آپارات",
    type: "سرگرمی",
    categories: "entertainmentApps",
    appVolume: 32,
  },
  {
    id: 34,
    img: "./src/images/apps-entertainment/app-entertainment-2.webp",
    title: "تلوبیون: پخش زنده و آرشیو تلویزیون",
    type: "سرگرمی",
    categories: "entertainmentApps",
    appVolume: 31,
  },
  {
    id: 35,
    img: "./src/images/apps-entertainment/app-entertainment-3.webp",
    title: "دیجیتون (کارتون و انیمیشن و موزیک)",
    type: "کودک",
    categories: "entertainmentApps",
    appVolume: 33,
  },
  {
    id: 36,
    img: "./src/images/apps-entertainment/app-entertainment-4.webp",
    title: "ارگ حرفه ای",
    type: "موسیقی",
    categories: "entertainmentApps",
    appVolume: 32,
  },
  {
    id: 37,
    img: "./src/images/apps-entertainment/app-entertainment-5.webp",
    title: "Paint By Number - Free Coloring Book & Puzzle Game",
    type: "تفتنی",
    categories: "entertainmentApps",
    appVolume: 34,
  },
  {
    id: 38,
    img: "./src/images/apps-entertainment/app-entertainment-6.webp",
    title: "Spotify - اسپاتیفای",
    type: "موسیقی",
    categories: "entertainmentApps",
    appVolume: 35,
  },
  {
    id: 39,
    img: "./src/images/apps-entertainment/app-entertainment-7.webp",
    title: "SoundCloud – پخش موسیقی ساند کلود",
    type: "موسیقی",
    categories: "entertainmentApps",
    appVolume: 36,
  },
  {
    id: 40,
    img: "./src/images/apps-entertainment/app-entertainment-8.webp",
    title: "Podcast Player App - Castbox",
    type: "موسیقی",
    categories: "entertainmentApps",
    appVolume: 21,
  },
  {
    id: 41,
    img: "./src/images/apps-entertainment/app-entertainment-9.webp",
    title: "Netflix - نتفلیکس",
    type: "سرگرمی",
    categories: "entertainmentApps",
    appVolume: 22,
  },
  {
    id: 42,
    img: "./src/images/apps-entertainment/app-entertainment-10.webp",
    title: "Beautycam- Selfie Editor",
    type: "عکاسی و ویدیو",
    categories: "entertainmentApps",
    appVolume: 23,
  },
  {
    id: 43,
    img: "./src/images/apps-entertainment/app-entertainment-11.webp",
    title: "ایران صدا - نسخه کامل",
    type: "موسیقی",
    categories: "entertainmentApps",
    appVolume: 24,
  },
  {
    id: 44,
    img: "./src/images/apps-entertainment/app-entertainment-12.webp",
    title: "ToonApp – تبدیل عکس به تصویر کارتونی",
    type: "عکاسی و ویدیو",
    categories: "entertainmentApps",
    appVolume: 25,
  },
  {
    id: 45,
    img: "./src/images/apps-entertainment/app-entertainment-13.webp",
    title: "Reddit – خبرخوان و تالار گفتگو ردیت",
    type: "شبکه های اجتماعی",
    categories: "entertainmentApps",
    appVolume: 23,
  },
  {
    id: 46,
    img: "./src/images/apps-entertainment/app-entertainment-14.webp",
    title: "Omlet Arcade – ضبط ویدیو از بازی",
    type: "عکاسی و ویدیو",
    categories: "entertainmentApps",
    appVolume: 27,
  },
  {
    id: 47,
    img: "./src/images/apps-entertainment/app-entertainment-15.webp",
    title: "Amazon Prime Video",
    type: "سرگرمی",
    categories: "entertainmentApps",
    appVolume: 28,
  },
  {
    id: 48,
    img: "./src/images/apps-entertainment/app-entertainment-16.webp",
    title: "Lark Player – پخش موسیقی",
    type: "موسیقی",
    categories: "entertainmentApps",
    appVolume: 29,
  },

  {
    id: 49,
    img: "./src/images/apps-social/app-social-1.webp",
    title: "imo-International Calls & Chat",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 19,
  },
  {
    id: 50,
    img: "./src/images/apps-social/app-social-2.webp",
    title: "Instagram Lite – اینستاگرام لایت",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 20,
  },
  {
    id: 51,
    img: "./src/images/apps-social/app-social-3.webp",
    title: "Skype",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 18,
  },
  {
    id: 52,
    img: "./src/images/apps-social/app-social-4.webp",
    title: "BeReal - بی ریل",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 17,
  },
  {
    id: 53,
    img: "./src/images/apps-social/app-social-5.webp",
    title: "نزدیکا - دایره دوستان جدید تو",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 18,
  },
  {
    id: 54,
    img: "./src/images/apps-social/app-social-6.webp",
    title: "باهم - دوستای جدید پیدا کن",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 16,
  },
  {
    id: 55,
    img: "./src/images/apps-social/app-social-7.webp",
    title: "پیام رسان ایتا",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 21,
  },
  {
    id: 56,
    img: "./src/images/apps-social/app-social-8.webp",
    title: "Plato - Games & Group Chats – چت گروهی و بازی پلاتو (افلاطون)",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 22,
  },
  {
    id: 57,
    img: "./src/images/apps-social/app-social-9.webp",
    title: "پاتوق - شبکه اجتماعی بازی و سرگرمی",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 23,
  },
  {
    id: 58,
    img: "./src/images/apps-social/app-social-10.webp",
    title: "ویسگون - شبکه اجتماعی فیلم و عکس",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 24,
  },
  {
    id: 59,
    img: "./src/images/apps-social/app-social-11.webp",
    title: "هورسا",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 25,
  },
  {
    id: 60,
    img: "./src/images/apps-social/app-social-12.webp",
    title: "بالونت – پیام ‌رسانی حرفه‌ای",
    type: "شبکه های اجتماعی",
    categories: "socialApps",
    appVolume: 26,
  },

  {
    id: 61,
    img: "./src/images/apps-musician/app-musician-1.webp",
    title: "Piano Kids - Music & Songs – پیانو برای کودکان",
    type: "کودک",
    categories: "musicianApps",
    appVolume: 14,
  },
  {
    id: 62,
    img: "./src/images/apps-musician/app-musician-2.webp",
    title: "ارگ 2023",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 13,
  },
  {
    id: 63,
    img: "./src/images/apps-musician/app-musician-3.webp",
    title: "ارگ حرفه ای",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 21,
  },
  {
    id: 64,
    img: "./src/images/apps-musician/app-musician-4.webp",
    title: "Real Piano",
    type: "تفتنی",
    categories: "musicianApps",
    appVolume: 14,
  },
  {
    id: 65,
    img: "./src/images/apps-musician/app-musician-5.webp",
    title: "ارگ ایرانی + ساخت موسیقی",
    type: "تفتنی",
    categories: "musicianApps",
    appVolume: 15,
  },
  {
    id: 66,
    img: "./src/images/apps-musician/app-musician-6.webp",
    title: "Real Guitar - Music Band Game",
    type: "تفتنی",
    categories: "musicianApps",
    appVolume: 16,
  },
  {
    id: 67,
    img: "./src/images/apps-musician/app-musician-7.webp",
    title: "Perfect Piano - پرفکت پیانو",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 17,
  },
  {
    id: 68,
    img: "./src/images/apps-musician/app-musician-8.webp",
    title: "Real Darbuka",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 18,
  },
  {
    id: 69,
    img: "./src/images/apps-musician/app-musician-9.webp",
    title: "Hang Drum Simulator",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 19,
  },
  {
    id: 70,
    img: "./src/images/apps-musician/app-musician-10.webp",
    title: "سنتور آموزشی",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 20,
  },
  {
    id: 71,
    img: "./src/images/apps-musician/app-musician-11.webp",
    title: "Piano - Music Keyboard & Tiles",
    type: "تفتنی",
    categories: "musicianApps",
    appVolume: 22,
  },
  {
    id: 72,
    img: "./src/images/apps-musician/app-musician-12.webp",
    title: "Real Drum: electronic drums",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 23,
  },
  {
    id: 73,
    img: "./src/images/apps-musician/app-musician-13.webp",
    title: "Kalimba Real",
    type: "شبیه سازی",
    categories: "musicianApps",
    appVolume: 24,
  },
  {
    id: 74,
    img: "./src/images/apps-musician/app-musician-14.webp",
    title: "X Drum - 3D & AR",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 25,
  },
  {
    id: 75,
    img: "./src/images/apps-musician/app-musician-15.webp",
    title: "Real Percussion: cumbia kit",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 26,
  },
  {
    id: 76,
    img: "./src/images/apps-musician/app-musician-16.webp",
    title: "Keylimba – کیلیمبا",
    type: "موسیقی",
    categories: "musicianApps",
    appVolume: 27,
  },

  {
    id: 77,
    img: "./src/images/apps-payment/app-payment-1.webp",
    title: "همراه من (اپلیکیشن رسمی همراه اول)",
    type: "ابزار ها",
    categories: "paymentApps",
    appVolume: 11,
  },
  {
    id: 78,
    img: "./src/images/apps-payment/app-payment-2.webp",
    title: "آپ کارت به کارت،خلافی خودرو،چک صیادی",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 10,
  },
  {
    id: 79,
    img: "./src/images/apps-payment/app-payment-3.webp",
    title: "هف هشتاد (#780*)",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 12,
  },
  {
    id: 80,
    img: "./src/images/apps-payment/app-payment-4.webp",
    title: "آی کاپ",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 13,
  },
  {
    id: 81,
    img: "./src/images/apps-payment/app-payment-5.webp",
    title: "رایتل من",
    type: "ابزار ها",
    categories: "paymentApps",
    appVolume: 14,
  },
  {
    id: 82,
    img: "./src/images/apps-payment/app-payment-6.webp",
    title: "تاپ (پرداخت عوارضی،کارت به کارت)",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 15,
  },
  {
    id: 83,
    img: "./src/images/apps-payment/app-payment-7.webp",
    title: "سکه - کارت به کارت بانک ملت، شارژ",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 16,
  },
  {
    id: 84,
    img: "./src/images/apps-payment/app-payment-8.webp",
    title: "ستاره یک - قبض، بلیت، شارژ و بسته",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 17,
  },
  {
    id: 85,
    img: "./src/images/apps-payment/app-payment-9.webp",
    title: "ایوا - خدمات پرداخت بانک ملی ایران",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 18,
  },
  {
    id: 86,
    img: "./src/images/apps-payment/app-payment-10.webp",
    title: "724 - اپلیکیشن پرداخت موبایلی",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 20,
  },
  {
    id: 87,
    img: "./src/images/apps-payment/app-payment-11.webp",
    title: "اوانو | کارت به کارت، شارژ، قبض",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 19,
  },
  {
    id: 88,
    img: "./src/images/apps-payment/app-payment-12.webp",
    title: "دیجی پی - اپلیکیشن پرداخت دیجی کالا",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 22,
  },
  {
    id: 89,
    img: "./src/images/apps-payment/app-payment-13.webp",
    title: "ساد24 | چک صیاد، وام فوری",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 21,
  },
  {
    id: 90,
    img: "./src/images/apps-payment/app-payment-14.webp",
    title: "قبضینو - قبض، خلافی خودرو و عوارض",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 23,
  },
  {
    id: 91,
    img: "./src/images/apps-payment/app-payment-15.webp",
    title: "پِی‌پاد(خلافی،کارت به کارت،شارژ)",
    type: "امور مالی",
    categories: "paymentApps",
    appVolume: 24,
  },

  {
    id: 92,
    img: "./src/images/apps-antivirus/app-antivirus-1.webp",
    title: "Virus Cleaner - Antivirus, Cleaner & Booster",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 25,
  },
  {
    id: 93,
    img: "./src/images/apps-antivirus/app-antivirus-2.webp",
    title: "آنتی ویروس قوی💪 و هوشمند",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 15,
  },
  {
    id: 94,
    img: "./src/images/apps-antivirus/app-antivirus-3.webp",
    title: "Kaspersky Security",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 25,
  },
  {
    id: 95,
    img: "./src/images/apps-antivirus/app-antivirus-4.webp",
    title: "360 Security - Antivirus, Booster, Phone Cleaner",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 27,
  },
  {
    id: 96,
    img: "./src/images/apps-antivirus/app-antivirus-5.webp",
    title: "Clean Master - Antivirus, Applock & Cleaner",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 17,
  },
  {
    id: 97,
    img: "./src/images/apps-antivirus/app-antivirus-6.webp",
    title: "ویروس کش قوی گوشی | موبو Security",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 18,
  },
  {
    id: 98,
    img: "./src/images/apps-antivirus/app-antivirus-7.webp",
    title: "آنتی ویروس دکتر وب - نسخه رایگان",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 19,
  },
  {
    id: 99,
    img: "./src/images/apps-antivirus/app-antivirus-8.webp",
    title: "Avast Antivirus & Security",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 23,
  },
  {
    id: 100,
    img: "./src/images/apps-antivirus/app-antivirus-9.webp",
    title: "Norton360 Antivirus & Security",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 32,
  },
  {
    id: 101,
    img: "./src/images/apps-antivirus/app-antivirus-10.webp",
    title: "بیت‌بان | ویروس کش، قفل برنامه و عکس",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 33,
  },
  {
    id: 102,
    img: "./src/images/apps-antivirus/app-antivirus-11.webp",
    title: "بیت‌بان | ویروس کش، قفل برنامه و عکس",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 35,
  },
  {
    id: 103,
    img: "./src/images/apps-antivirus/app-antivirus-12.webp",
    title: "dfndr security: antivirus",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 37,
  },
  {
    id: 104,
    img: "./src/images/apps-antivirus/app-antivirus-13.webp",
    title: "AVG AntiVirus & Security",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 17,
  },
  {
    id: 105,
    img: "./src/images/apps-antivirus/app-antivirus-14.webp",
    title: "One Booster – پاک کننده و آنتی ویروس وان بوستر",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 24,
  },
  {
    id: 106,
    img: "./src/images/apps-antivirus/app-antivirus-15.webp",
    title: "One Security - آنتی ویروس و بهینه ساز گوشی وان سکیوریتی",
    type: "ابزار ها",
    categories: "antivirusApps",
    appVolume: 20,
  },

  {
    id: 107,
    img: "./src/images/apps-editors/app-editors-1.webp",
    title: "پادباکس پلاس",
    type: "سرگرمی",
    categories: "EditorsApps",
    appVolume: 15,
  },
  {
    id: 108,
    img: "./src/images/apps-editors/app-editors-2.webp",
    title: "فراز (همراه بانک ایران زمین)  ",
    type: "امور مالی",
    categories: "EditorsApps",
    appVolume: 16,
  },
  {
    id: 109,
    img: "./src/images/apps-editors/app-editors-3.webp",
    title: "حسابدار اپ | مشاوره مالیات آنلاین",
    type: "امور مالی",
    categories: "EditorsApps",
    appVolume: 17,
  },
  {
    id: 110,
    img: "./src/images/apps-editors/app-editors-4.webp",
    title: "زبانیموز | اموزش زبان با فیلم",
    type: "آموزش",
    categories: "EditorsApps",
    appVolume: 18,
  },
  {
    id: 111,
    img: "./src/images/apps-editors/app-editors-5.webp",
    title: "واید خدمات بانکی،خلافی،قبوض",
    type: "امور مالی",
    categories: "EditorsApps",
    appVolume: 14,
  },
  {
    id: 112,
    img: "./src/images/apps-editors/app-editors-6.webp",
    title: "English Phrasal Verbs",
    type: "آموزش",
    categories: "EditorsApps",
    appVolume: 13,
  },
  {
    id: 113,
    img: "./src/images/apps-editors/app-editors-7.webp",
    title: "کارتون های کودکانه ویدزی",
    type: "کودک",
    categories: "EditorsApps",
    appVolume: 12,
  },
  {
    id: 114,
    img: "./src/images/apps-editors/app-editors-8.webp",
    title: "دکتردکتر | نوبت دکتر و مشاوره پزشکی",
    type: "پزشکی",
    categories: "EditorsApps",
    appVolume: 11,
  },
  {
    id: 115,
    img: "./src/images/apps-editors/app-editors-9.webp",
    title: "تاکسی یوز | سفرهای شهری و بین‌شهری",
    type: "رفت و آمد",
    categories: "EditorsApps",
    appVolume: 40,
  },
  {
    id: 116,
    img: "./src/images/apps-editors/app-editors-10.webp",
    title: "Sky Tonight - Star Gazer Guide",
    type: "کتاب و مطبوعات",
    categories: "EditorsApps",
    appVolume: 9,
  },
  {
    id: 117,
    img: "./src/images/apps-editors/app-editors-11.webp",
    title: "آموزش زبان انگلیسی یوز",
    type: "آموزش",
    categories: "EditorsApps",
    appVolume: 25,
  },
  {
    id: 118,
    img: "./src/images/apps-editors/app-editors-12.webp",
    title: "«دید» میلیون‌ها ایده تصویری جذاب",
    type: "سبک زندگی",
    categories: "EditorsApps",
    appVolume: 9,
  },
  {
    id: 119,
    img: "./src/images/apps-editors/app-editors-13.webp",
    title: "آموزش زبان انگلیسی - دایموند",
    type: "آموزش",
    categories: "EditorsApps",
    appVolume: 21,
  },
  {
    id: 120,
    img: "./src/images/apps-editors/app-editors-14.webp",
    title: "مامانا | بارداری هفته به هفته",
    type: "پزشکی",
    categories: "EditorsApps",
    appVolume: 12,
  },
  {
    id: 121,
    img: "./src/images/apps-editors/app-editors-15.webp",
    title: "هپی تون | انیمیشن های انگلیسی",
    type: "کودک",
    categories: "EditorsApps",
    appVolume: 21,
  },

  {
    id: 122,
    img: "./src/images/update-editors-app/update-editors-1.webp",
    title: "لایتنر زبان جیب (فلش کارت)",
    type: "آموزش",
    categories: "EditorsUpdateApps",
    appVolume: 12,
  },
  {
    id: 123,
    img: "./src/images/update-editors-app/update-editors-2.webp",
    title: "ویپاد | تَرابانک پاسارگاد",
    type: "امور مالی",
    categories: "EditorsUpdateApps",
    appVolume: 24,
  },
  {
    id: 124,
    img: "./src/images/update-editors-app/update-editors-3.webp",
    title: "همراه تریدر نوبیتکس",
    type: "امور مالی",
    categories: "EditorsUpdateApps",
    appVolume: 5,
  },
  {
    id: 125,
    img: "./src/images/update-editors-app/update-editors-4.webp",
    title: "ویسگون - شبکه اجتماعی فیلم و عکس",
    type: "شبکه های اجتماعی",
    categories: "EditorsUpdateApps",
    appVolume: 6,
  },
  {
    id: 126,
    img: "./src/images/update-editors-app/update-editors-5.webp",
    title: "Digital Wellbeing – سلامت دیجیتال",
    type: "ابزار ها",
    categories: "EditorsUpdateApps",
    appVolume: 7,
  },
  {
    id: 127,
    img: "./src/images/update-editors-app/update-editors-6.webp",
    title: "آیدی پی(عوارض،کارت به کارت،شارژمترو)",
    type: "امور مالی",
    categories: "EditorsUpdateApps",
    appVolume: 8,
  },
  {
    id: 128,
    img: "./src/images/update-editors-app/update-editors-7.webp",
    title: "آیتول (خلافی خودرو، بیمه، عوارض)",
    type: "امور مالی",
    categories: "EditorsUpdateApps",
    appVolume: 9,
  },
  {
    id: 129,
    img: "./src/images/update-editors-app/update-editors-8.webp",
    title: "دیجی‌کالا | فروشگاه خرید آنلاین",
    type: "خرید",
    categories: "EditorsUpdateApps",
    appVolume: 10,
  },
  {
    id: 130,
    img: "./src/images/update-editors-app/update-editors-9.webp",
    title: "فام(اپلیکیشن بانکی آنلاین)",
    type: "امور مالی",
    categories: "EditorsUpdateApps",
    appVolume: 11,
  },
  {
    id: 131,
    img: "./src/images/update-editors-app/update-editors-10.webp",
    title: "آچاره | خدمات و تعمیرات در منزل",
    type: "سبک زندگی",
    categories: "EditorsUpdateApps",
    appVolume: 12,
  },
  {
    id: 132,
    img: "./src/images/update-editors-app/update-editors-11.webp",
    title: "اسنپ |Snapp سامانه هوشمند حمل و نقل",
    type: "رفت و آمد",
    categories: "EditorsUpdateApps",
    appVolume: 13,
  },
  {
    id: 133,
    img: "./src/images/update-editors-app/update-editors-12.webp",
    title: "فیلم‌نت - تماشای فیلم و سریال",
    type: "سرگرمی",
    categories: "EditorsUpdateApps",
    appVolume: 14,
  },
  {
    id: 134,
    img: "./src/images/update-editors-app/update-editors-13.webp",
    title: "همراه بانک ملت",
    type: "امور مالی",
    categories: "EditorsUpdateApps",
    appVolume: 15,
  },
  {
    id: 135,
    img: "./src/images/update-editors-app/update-editors-14.webp",
    title: "SHAREit - شیر ایت",
    type: "ابزار ها",
    categories: "EditorsUpdateApps",
    appVolume: 16,
  },
  {
    id: 136,
    img: "./src/images/update-editors-app/update-editors-15.webp",
    title: "ارگ حرفه ای",
    type: "موسیقی",
    categories: "EditorsUpdateApps",
    appVolume: 17,
  },
  {
    id: 137,
    img: "./src/images/update-editors-app/update-editors-16.webp",
    title: "همیارزبان - آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "EditorsUpdateApps",
    appVolume: 18,
  },

  {
    id: 138,
    img: "./src/images/apps-english/app-english-1.webp",
    title: "لِرنیت | آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 22,
  },
  {
    id: 139,
    img: "./src/images/apps-english/app-english-2.webp",
    title: "Duolingo – آموزش زبان دولینگو",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 12,
  },
  {
    id: 140,
    img: "./src/images/apps-english/app-english-3.webp",
    title: "زبان بیاموز",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 13,
  },
  {
    id: 141,
    img: "./src/images/apps-english/app-english-4.webp",
    title: "زبانشناس: آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 14,
  },
  {
    id: 142,
    img: "./src/images/apps-english/app-english-5.webp",
    title: "همیارزبان - آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 15,
  },
  {
    id: 143,
    img: "./src/images/apps-english/app-english-6.webp",
    title: "دهکده زبان | آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 16,
  },
  {
    id: 144,
    img: "./src/images/apps-english/app-english-7.webp",
    title: "HelloTalk – گفتگو و آموزش زبان هلو تاک",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 17,
  },
  {
    id: 145,
    img: "./src/images/apps-english/app-english-8.webp",
    title: "Learn English free – آموزش رایگان زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 18,
  },
  {
    id: 146,
    img: "./src/images/apps-english/app-english-9.webp",
    title: "Drops - آموزش زبان",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 19,
  },
  {
    id: 147,
    img: "./src/images/apps-english/app-english-10.webp",
    title: "Busuu – یادگیری زبان",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 20,
  },
  {
    id: 148,
    img: "./src/images/apps-english/app-english-11.webp",
    title: "آموزش زبان انگلیسی اطلس",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 31,
  },
  {
    id: 149,
    img: "./src/images/apps-english/app-english-12.webp",
    title: "بلبل | آموزش زبان",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 32,
  },
  {
    id: 150,
    img: "./src/images/apps-english/app-english-13.webp",
    title: "English Conversation Practice - تمرین مکالمات انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 33,
  },
  {
    id: 151,
    img: "./src/images/apps-english/app-english-14.webp",
    title: "زبانیاد | آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 34,
  },
  {
    id: 152,
    img: "./src/images/apps-english/app-english-15.webp",
    title: "لینگوگیم - بازی آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 35,
  },
  {
    id: 153,
    img: "./src/images/apps-english/app-english-16.webp",
    title: "بامبو | شهر زبان | انگلیسی و آلمانی ",
    type: "آموزش",
    categories: "languageApps",
    appVolume: 36,
  },
  {
    id: 156,
    img: "./src/images/apps-photo-editing/app-photo-editing-1.webp",
    title: "Beautycam- Selfie Editor",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 37,
  },
  {
    id: 157,
    img: "./src/images/apps-photo-editing/app-photo-editing-2.webp",
    title: "Lumii – ویرایش تصویر",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 38,
  },
  {
    id: 158,
    img: "./src/images/apps-photo-editing/app-photo-editing-3.webp",
    title: "Adobe Lightroom – ویرایش تصویر",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 39,
  },
  {
    id: 159,
    img: "./src/images/apps-photo-editing/app-photo-editing-4.webp",
    title: "Snapseed – ویرایشگر عکس اسنپ سید",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 34,
  },
  {
    id: 160,
    img: "./src/images/apps-photo-editing/app-photo-editing-5.webp",
    title: "Picsart Lite: Photo Editor",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 40,
  },
  {
    id: 161,
    img: "./src/images/apps-photo-editing/app-photo-editing-6.webp",
    title: "StoryArt – طراحی استوری اینستاگرام",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 41,
  },
  {
    id: 162,
    img: "./src/images/apps-photo-editing/app-photo-editing-7.webp",
    title: "Collage Maker | Photo Editor",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 42,
  },
  {
    id: 163,
    img: "./src/images/apps-photo-editing/app-photo-editing-8.webp",
    title: "Pixlr – Photo Editor",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 43,
  },
  {
    id: 164,
    img: "./src/images/apps-photo-editing/app-photo-editing-9.webp",
    title: "MakeupPlus - Virtual Makeup",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 44,
  },
  {
    id: 165,
    img: "./src/images/apps-photo-editing/app-photo-editing-10.webp",
    title: "Gradient",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 45,
  },
  {
    id: 166,
    img: "./src/images/apps-photo-editing/app-photo-editing-11.webp",
    title: "Photo Editor",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 46,
  },
  {
    id: 167,
    img: "./src/images/apps-photo-editing/app-photo-editing-12.webp",
    title: "Photo Editor",
    type: "عکاسی و ویدیو",
    categories: "photoEditingApps",
    appVolume: 47,
  },
  {
    id: 168,
    img: "./src/images/apps-low-volume/app-low-volume-1.webp",
    title: "ZArchiver",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 3,
  },
  {
    id: 169,
    img: "./src/images/apps-low-volume/app-low-volume-2.webp",
    title: "تقویم اذان گو بادصبا",
    type: "مذهبی",
    categories: "lowAppsVolume",
    appVolume: 9,
  },
  {
    id: 170,
    img: "./src/images/apps-low-volume/app-low-volume-3.webp",
    title: "دیوار",
    type: "خرید",
    categories: "lowAppsVolume",
    appVolume: 4,
  },
  {
    id: 171,
    img: "./src/images/apps-low-volume/app-low-volume-4.webp",
    title: "تیکاسا - برنامه‌ریزی و مدیریت‌ کارها",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 5,
  },
  {
    id: 172,
    img: "./src/images/apps-low-volume/app-low-volume-5.webp",
    title: "Tripadvisor: Plan & Book Trips",
    type: "سفر",
    categories: "lowAppsVolume",
    appVolume: 6,
  },
  {
    id: 173,
    img: "./src/images/apps-low-volume/app-low-volume-6.webp",
    title: "Recover Deleted Photos by Dumpster",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 7,
  },
  {
    id: 174,
    img: "./src/images/apps-low-volume/app-low-volume-7.webp",
    title: "Barcode Scanner",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 8,
  },
  {
    id: 175,
    img: "./src/images/apps-low-volume/app-low-volume-8.webp",
    title: "همیارزبان - آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "lowAppsVolume",
    appVolume: 9,
  },
  {
    id: 176,
    img: "./src/images/apps-low-volume/app-low-volume-9.webp",
    title: "Vault - Hide Pics, App Lock",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 10,
  },
  {
    id: 177,
    img: "./src/images/apps-low-volume/app-low-volume-10.webp",
    title: "imo-International Calls & Chat",
    type: "شبکه های اجتماعی",
    categories: "lowAppsVolume",
    appVolume: 11,
  },
  {
    id: 178,
    img: "./src/images/apps-low-volume/app-low-volume-11.webp",
    title: "Clean Master - Antivirus, Applock & Cleaner",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 12,
  },
  {
    id: 179,
    img: "./src/images/apps-low-volume/app-low-volume-12.webp",
    title: "Google Go - جستجوی ساده و سریع",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 13,
  },
  {
    id: 180,
    img: "./src/images/apps-low-volume/app-low-volume-13.webp",
    title: "AZ Screen Recorder ‏ - ضبط ویدیو از صفحه گوشی",
    type: "عکاسی و ویدیو",
    categories: "lowAppsVolume",
    appVolume: 14,
  },
  {
    id: 181,
    img: "./src/images/apps-low-volume/app-low-volume-14.webp",
    title: "پیگیری مرسولات پستی",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 15,
  },
  {
    id: 182,
    img: "./src/images/apps-low-volume/app-low-volume-15.webp",
    title: "Google Keep - Notes and Lists",
    type: "ابزار ها",
    categories: "lowAppsVolume",
    appVolume: 16,
  },
  {
    id: 183,
    img: "./src/images/apps-low-volume/app-low-volume-16.webp",
    title: "پاکسیت: خرید گیفت کارت بازی و برنامه",
    type: "خرید",
    categories: "lowAppsVolume",
    appVolume: 17,
  },
  {
    id: 184,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-1.webp",
    title: "سیگما - مدیریت اینترنت WiFi/4G/3G",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 18,
  },
  {
    id: 185,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-2.webp",
    title: "Live Transcribe - تبدیل گفتار به متن",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 19,
  },
  {
    id: 186,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-3.webp",
    title: "Adobe Acrobat Reader: Edit PDF",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 20,
  },
  {
    id: 187,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-4.webp",
    title: "AppLock",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 21,
  },
  {
    id: 188,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-5.webp",
    title: "AVG Cleaner – Storage Cleaner",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 22,
  },
  {
    id: 189,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-6.webp",
    title: "Cache Cleaner-DU Speed Booster (booster & cleaner)",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 23,
  },
  {
    id: 190,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-7.webp",
    title: "Greenify",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 24,
  },
  {
    id: 191,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-8.webp",
    title: "زی‌تایپ | تایپ صوتی دیپ‌ماین",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 25,
  },
  {
    id: 192,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-9.webp",
    title: "آنتی ویروس دکتر وب - نسخه رایگان",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 26,
  },
  {
    id: 193,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-10.webp",
    title: "Clean Master - Antivirus, Applock & Cleaner",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 27,
  },
  {
    id: 194,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-11.webp",
    title: "جعبه ابزار ",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 28,
  },
  {
    id: 195,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-12.webp",
    title: "Antivirus - آنتی ویروس،‌ قفل برنامه و خنک کننده‌ی گوشی",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 29,
  },
  {
    id: 196,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-13.webp",
    title: "Google Keep - Notes and Lists",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 30,
  },
  {
    id: 197,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-14.webp",
    title: "Super Backup & Restore",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 31,
  },
  {
    id: 198,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-15.webp",
    title: "چفتک ( قفل برنامه - گالری مخفی)",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 32,
  },
  {
    id: 199,
    img: "./src/images/apps-mobile-tools/app-mobile-tools-16.webp",
    title: "CamScanner - PDF Scanner App",
    type: "ابزار ها",
    categories: "toolsApps",
    appVolume: 33,
  },

  {
    id: 200,
    img: "./src/images/apps-hottest-others/app-hottest-others-1.webp",
    title: "همراه بام ملی ",
    type: "امور مالی",
    categories: "hottestApps",
    appVolume: 34,
  },
  {
    id: 201,
    img: "./src/images/apps-hottest-others/app-hottest-others-2.webp",
    title: "نشان | نقشه و مسیریاب",
    type: "رفت و آمد",
    categories: "hottestApps",
    appVolume: 35,
  },
  {
    id: 202,
    img: "./src/images/apps-hottest-others/app-hottest-others-3.webp",
    title: "اپلیکیشن شاد",
    type: "آموزش",
    categories: "hottestApps",
    appVolume: 36,
  },
  {
    id: 203,
    img: "./src/images/apps-hottest-others/app-hottest-others-4.webp",
    title: "روبیکا X",
    type: "شبکه های اجتماعی",
    categories: "hottestApps",
    appVolume: 37,
  },
  {
    id: 204,
    img: "./src/images/apps-hottest-others/app-hottest-others-5.webp",
    title: "ایتا Eitaa کلینر ",
    type: "شبکه های اجتماعی",
    categories: "hottestApps",
    appVolume: 38,
  },
  {
    id: 205,
    img: "./src/images/apps-hottest-others/app-hottest-others-6.webp",
    title: "مفاتیح الجنان صوتی باب النعیم ",
    type: "مذهبی",
    categories: "hottestApps",
    appVolume: 39,
  },
  {
    id: 206,
    img: "./src/images/apps-hottest-others/app-hottest-others-7.webp",
    title: "دانلود وضعیت واتساپ",
    type: "شبکه های اجتماعی",
    categories: "hottestApps",
    appVolume: 40,
  },
  {
    id: 207,
    img: "./src/images/apps-hottest-others/app-hottest-others-8.webp",
    title: "او ام پی فینکس (ompfinex)",
    type: "امور مالی",
    categories: "hottestApps",
    appVolume: 41,
  },
  {
    id: 208,
    img: "./src/images/apps-hottest-others/app-hottest-others-9.webp",
    title: "Files by Google",
    type: "ابزار ها",
    categories: "hottestApps",
    appVolume: 42,
  },
  {
    id: 209,
    img: "./src/images/apps-hottest-others/app-hottest-others-10.webp",
    title: "مستربلیط | خرید بلیط سفر، رزرو هتل",
    type: "سفر",
    categories: "hottestApps",
    appVolume: 43,
  },
  {
    id: 210,
    img: "./src/images/apps-hottest-others/app-hottest-others-11.webp",
    title: "آموزش کامل برنامه شاد ",
    type: "آموزش",
    categories: "hottestApps",
    appVolume: 44,
  },
  {
    id: 211,
    img: "./src/images/apps-hottest-others/app-hottest-others-12.webp",
    title: "آنفالویاب هوشمند همه‌کاره + دانلودر",
    type: "شبکه های اجتماعی",
    categories: "hottestApps",
    appVolume: 45,
  },
  {
    id: 212,
    img: "./src/images/apps-hottest-others/app-hottest-others-13.webp",
    title: "ایتا Eitaa کلینر",
    type: "ابزار ها",
    categories: "hottestApps",
    appVolume: 46,
  },
  {
    id: 213,
    img: "./src/images/apps-best-seller/app-best-seller-1.webp",
    title: "دیوار",
    type: "خرید",
    categories: "bestSellerApps",
    appVolume: 9,
  },
  {
    id: 214,
    img: "./src/images/apps-best-seller/app-best-seller-2.webp",
    title: "فیلیمو - تماشای فیلم و سریال",
    type: "سرگرمی",
    categories: "bestSellerApps",
    appVolume: 10,
  },
  {
    id: 215,
    img: "./src/images/apps-best-seller/app-best-seller-3.webp",
    title: "فیلم‌نت - تماشای فیلم و سریال",
    type: "سرگرمی",
    categories: "bestSellerApps",
    appVolume: 11,
  },
  {
    id: 216,
    img: "./src/images/apps-best-seller/app-best-seller-4.webp",
    title: "نماوا - تماشای آنلاین فیلم و سریال",
    type: "سرگرمی",
    categories: "bestSellerApps",
    appVolume: 12,
  },
  {
    id: 217,
    img: "./src/images/apps-best-seller/app-best-seller-5.webp",
    title: "طاقچه | دانلود کتاب صوتی و الکترونیک",
    type: "کتاب و مطبوعات",
    categories: "bestSellerApps",
    appVolume: 13,
  },
  {
    id: 218,
    img: "./src/images/apps-best-seller/app-best-seller-6.webp",
    title: "شیپور: خرید و فروش خودرو، ملک و ...",
    type: "خرید",
    categories: "bestSellerApps",
    appVolume: 14,
  },
  {
    id: 219,
    img: "./src/images/apps-best-seller/app-best-seller-7.webp",
    title: "باهم - دوستای جدید پیدا کن",
    type: "شبکه های اجتماعی",
    categories: "bestSellerApps",
    appVolume: 15,
  },
  {
    id: 220,
    img: "./src/images/apps-best-seller/app-best-seller-8.webp",
    title: "عضو بگیر کانال روبیکا",
    type: "شبکه های اجتماعی",
    categories: "bestSellerApps",
    appVolume: 16,
  },
  {
    id: 221,
    img: "./src/images/apps-best-seller/app-best-seller-9.webp",
    title: "کرفس - سلامتی، رژیم و تناسب اندام",
    type: "تناسب اندام",
    categories: "bestSellerApps",
    appVolume: 17,
  },
  {
    id: 222,
    img: "./src/images/apps-best-seller/app-best-seller-10.webp",
    title: "راننده آسان‌بار-اعلام بار لحظه‌‌ای",
    type: "رفت و آمد",
    categories: "bestSellerApps",
    appVolume: 18,
  },
  {
    id: 223,
    img: "./src/images/apps-best-seller/app-best-seller-11.webp",
    title: "فیدیبو |دانلود کتاب الکترونیک و صوتی",
    type: "کتاب و مطبوعات",
    categories: "bestSellerApps",
    appVolume: 15,
  },
  {
    id: 224,
    img: "./src/images/apps-best-seller/app-best-seller-12.webp",
    title: "فالوور بگیر روبیکا و روبینو",
    type: "شبکه های اجتماعی",
    categories: "bestSellerApps",
    appVolume: 25,
  },
  {
    id: 225,
    img: "./src/images/apps-best-seller/app-best-seller-13.webp",
    title: "زبانشناس: آموزش زبان انگلیسی",
    type: "آموزش",
    categories: "bestSellerApps",
    appVolume: 24,
  },
  {
    id: 226,
    img: "./src/images/apps-best-seller/app-best-seller-14.webp",
    title: "گهواره: بارداری و کودک",
    type: "پزشکی",
    categories: "bestSellerApps",
    appVolume: 23,
  },
  {
    id: 227,
    img: "./src/images/apps-best-seller/app-best-seller-15.webp",
    title: "لایک بگیر اینستاگرام",
    type: "شبکه های اجتماعی",
    categories: "bestSellerApps",
    appVolume: 22,
  },
  {
    id: 228,
    img: "./src/images/apps-best-seller/app-best-seller-16.webp",
    title: "گپ‌فیلم - دانلود و تماشای نامحدود",
    type: "سرگرمی",
    categories: "bestSellerApps",
    appVolume: 21,
  },
];

export default allAppData;
